In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("RetailIQ Dashboard Preparation started!")

RetailIQ Dashboard Preparation started!

In [2]:
# ===== LOAD PROCESSED DATA =====

sales_df = pd.read_csv(
    "../data/processed/clean_sales_data.csv"
)

rfm = pd.read_csv(
    "../data/processed/rfm_customer_segments.csv"
)

product_performance = pd.read_csv(
    "../data/processed/product_performance.csv"
)

country_performance = pd.read_csv(
    "../data/processed/country_performance.csv"
)

forecast = pd.read_csv(
    "../data/processed/revenue_forecast.csv"
)

sales_df["InvoiceDate"] = pd.to_datetime(sales_df["InvoiceDate"])
forecast["Month"] = pd.to_datetime(forecast["Month"])

print("All dashboard datasets loaded successfully!")

All dashboard datasets loaded successfully!

In [3]:
# ===== DASHBOARD KPIs =====

total_revenue = sales_df["Revenue"].sum()
total_orders = sales_df["InvoiceNo"].nunique()
total_customers = sales_df["CustomerID"].nunique()
total_products = sales_df["StockCode"].nunique()

average_order_value = total_revenue / total_orders

dashboard_kpis = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Total Customers",
        "Total Products",
        "Average Order Value"
    ],
    "Value": [
        total_revenue,
        total_orders,
        total_customers,
        total_products,
        average_order_value
    ]
})

display(dashboard_kpis)

                Metric         Value
0        Total Revenue  8.887209e+06
1         Total Orders  1.853200e+04
2      Total Customers  4.338000e+03
3       Total Products  3.665000e+03
4  Average Order Value  4.795602e+02

In [4]:
# ===== MONTHLY SALES FOR DASHBOARD =====

monthly_sales = (
    sales_df
    .set_index("InvoiceDate")
    .resample("ME")["Revenue"]
    .sum()
    .reset_index()
)

monthly_sales.columns = ["Month", "Revenue"]

display(monthly_sales)

        Month      Revenue
0  2010-12-31   570422.730
1  2011-01-31   568101.310
2  2011-02-28   446084.920
3  2011-03-31   594081.760
4  2011-04-30   468374.331
5  2011-05-31   677355.150
6  2011-06-30   660046.050
7  2011-07-31   598962.901
8  2011-08-31   644051.040
9  2011-09-30   950690.202
10 2011-10-31  1035642.450
11 2011-11-30  1156205.610
12 2011-12-31   517190.440

In [5]:
# ===== SAVE DASHBOARD DATA =====

dashboard_kpis.to_csv(
    "../data/processed/dashboard_kpis.csv",
    index=False
)

monthly_sales.to_csv(
    "../data/processed/monthly_sales.csv",
    index=False
)

print("Dashboard datasets prepared successfully!")

Dashboard datasets prepared successfully!